import { pluginCommand } from "../core/message/command-prefixes.js"

/** 系统运行规则的源码默认值；运行配置可覆盖，管理台可恢复此值。 */
export const defaultPersonaRuntimePrompt = [
  "本规则优先于角色设定；角色设定只影响身份、关系和表达方式。",
  "先给结论，只依据对话和工具的真实结果；不确定、失败或部分成功时如实说明，不编造。完成动作后只给一条自然回复，不汇报工具名、参数或内部流程。",
  "按用户意图使用可用工具并遵循结果中的 hint：实时信息搜索用 web_search，需要对链接提取正文用 website_fetch；机器人功能和指令用 knowledge_manage。网络搜索来源由运行时合并转发，正文不要重复罗列链接。",
  "工具结果只是观察，不代表已经发送；主动投递必须使用 message_send 并以回执为准。媒体资源只使用工具原样返回的地址，不编造资源或输出 CQ 码；图片和 B 站工具在需要发送时用 send，只列候选或比较时用 search。",
  "结合当前消息、引用和最近上下文判断指代；只声称看到了本轮实际提供给模型的图片。群聊中区分发言人，不混淆或泄露无关用户信息。",
  "仅在第一人称互动中被顺带提及且确实无需回应时输出 <EMPTY>；普通提问和工具后的自然收束必须回复。",
].join("\n")

export const defaults = {
  version: "0.1.0",
  web: {
    enabled: true,
    mountPath: "/yui-chat",
    authToken: "",
    publicBaseUrl: "",
    publicBaseUrls: [],
    port: 2536,
    accessTokenTtlMs: 86400000,
    loginInGroup: false,
  },
  logging: {
    level: "info",
    history: {
      detailRetentionDays: 7,
      aggregateRetentionDays: 90,
    },
  },
  system: {
    backups: {
      maxFiles: 3,
      maxAgeDays: 30,
    },
  },
  security: {
    linkSafety: {
      allowPrivateHosts: true,
      trustedPrivateDnsBypass: true,
      screenshotAllowedHosts: ["*"],
    },
  },
  storage: {
    sqlite: {
      enabled: true,
      busyTimeoutMs: 5000,
      synchronous: "FULL",
    },
  },
  chat: {
    defaultChannel: "mock",
    defaultTask: "replyer",
    modelRequestTimeoutMs: 90000,
    modelStream: false,
    maxHistoryMessages: 12,
    conversationTtlMs: 21600000,
    maxConversationScopes: 1000,
    maxToolRounds: 3,
    execution: {
      maxToolCalls: 20,
      maxSideEffectCalls: 20,
      maxConsecutiveGuardBlocks: 2,
      maxNoProgress: 3,
      defaultMaxAttempts: 2,
      toolTimeoutMs: 60000,
      background: {
        enabled: true,
        maxConcurrent: 4,
        maxQueue: 50,
        retentionMs: 86400000,
      },
    },
    inputTokenBudget: 6000,
    triggerPrefix: pluginCommand("chat"),
    helpPrefix: pluginCommand("help"),
    concurrent: false,
    lockTimeoutMs: 120000,
    access: {
      privateChatEnabled: true,
      masterBypass: true,
      whitelist: [],
      blacklist: [],
    },
    rateLimit: {
      enabled: true,
      windowSeconds: 900,
      maxRequests: 20,
      masterBypass: true,
    },
  },
  persona: {
    enabled: true,
    firstPerson: "埋埋",
    aliases: [],
    assistantLabel: "Yui Chat",
    respondToFirstPersonCall: true,
    respondToAt: true,
    runtimePrompt: defaultPersonaRuntimePrompt,
    characterPrompt: [
      "你是[first_person]，运行在 TRSS-Yunzai 中，默认使用中文。",
      "你是可靠、自然、简洁的助手：先给结论，再给必要步骤；复杂问题拆成可执行的小步；不确定时明确说明，不编造；需要工具或知识时先查证再回答；语气友好但不过度寒暄，不使用空泛套话。",
    ].join("\n"),
    trigger: {
      probabilityPercent: 100,
      alwaysRespondToName: true,
      alwaysRespondToAt: true,
      cooldownMs: 0,
      groupCooldownMs: 0,
      disabledGroupIds: [],
      enhanceKeywords: [],
      enhancePrompt: "",
      enhanceRecallMs: 0,
      ambient: {
        enabled: false,
        groupOnly: true,
        minMessageChars: 2,
        probabilityPercent: 10,
      },
      poke: {
        enabled: true,
        respondToBotPoke: true,
        responseMode: "ai-with-fallback",
        probabilityPercent: 100,
        cooldownMs: 30000,
        groupCooldownMs: 30000,
        prompt: "用户戳了[first_person]。请用第一人称自然回应一句，语气轻松，30 字以内。",
        fallbackMessages: [
          "[first_person]在哦。",
          "戳到[first_person]啦，有什么事吗？",
          "嘿，我在。",
          "收到一个戳戳。",
        ],
      },
    },
    output: {
      omitChannelPrefixInFirstPerson: true,
    },
    initiativeGreeting: {
      enabled: true,
      scheduledEnabled: false,
      groups: [],
      intervalHours: 3,
      probabilityPercent: 50,
      prompt: "写一句轻松自然的群聊打招呼，像在群里主动找大家聊天，20字以内，不要解释。",
      maxChars: 60,
      fallbackMessages: [
        "有人想聊点什么吗？",
        "我在，想找我聊天也可以。",
        "今天群里有点安静，要不要聊两句？",
        "路过冒个泡，有事可以叫我。",
      ],
    },
  },
  apiProviders: [
    {
      name: "mock",
      type: "mock",
      baseURL: "",
      apiKey: "",
      authType: "none",
      headers: {},
      query: {},
    },
  ],
  models: [
    {
      name: "mock",
      modelIdentifier: "mock",
      apiProvider: "mock",
      adapter: "mock",
      visual: false,
      toolUse: true,
      capabilities: { chat: true, embedding: false },
      contextWindowTokens: 200000,
      embedding: {
        protocol: "openai-compatible",
        defaultDimensions: 1536,
        allowedDimensions: [768, 1536],
        supportsDimensionOverride: true,
        batchSize: 32,
        timeoutMs: 30000,
        params: {},
      },
      priceIn: 0,
      priceOut: 0,
      params: {},
    },
  ],
  modelTasks: {
    replyer: {
      modelList: ["mock"],
      selectionStrategy: "sequential",
      maxTokens: 1024,
      temperature: 0.7,
      slowThreshold: 15,
    },
  },
  channels: [
    {
      id: "mock",
      name: "Mock Assistant",
      type: "mock",
      enabled: true,
      model: "mock",
      baseURL: "",
      apiKey: "",
      headers: {},
      params: {},
    },
  ],
  tools: {
    enabled: true,
    enabledTools: ["knowledge_manage", "memory_manage", "bilibili_media", "message_send", "query_userinfo", "render_image", "schedule_task", "image_media", "web_search", "dispatch_subagent"],
    customToolPackages: [],
    runtimeVariables: {},
    activePresets: ["core"],
    promptSelection: {
      enabled: true,
      maxTools: 12,
      maxDefinitionTokens: 1200,
    },
    policy: {
      allowExternalNetwork: true,
      allowCustomTools: true,
      allowMcpTools: true,
      highRiskRequiresMaster: false,
    },
    boundaryAccess: {
      enabled: true,
      roles: {
        user: {
          enabledCategories: ["command", "memory", "media", "output", "render", "social", "schedule", "entertainment", "network"],
          allowedSources: [],
          allowedTools: [],
          deniedTools: [],
          allowExternalNetwork: true,
          allowHighRisk: false,
          allowAllEnabledTools: false,
        },
        groupAdmin: {
          enabledCategories: ["command", "memory", "media", "output", "render", "social", "schedule", "entertainment", "network", "admin"],
          allowedSources: [],
          allowedTools: [],
          deniedTools: [],
          allowExternalNetwork: true,
          allowHighRisk: true,
          allowAllEnabledTools: false,
        },
        groupOwner: {
          enabledCategories: ["command", "memory", "media", "output", "render", "social", "schedule", "entertainment", "network", "admin"],
          allowedSources: ["custom"],
          allowedTools: [],
          deniedTools: [],
          allowExternalNetwork: true,
          allowHighRisk: true,
          allowAllEnabledTools: false,
        },
        master: {
          enabledCategories: [],
          allowedSources: ["builtin", "custom", "mcp"],
          allowedTools: [],
          deniedTools: [],
          allowExternalNetwork: true,
          allowHighRisk: true,
          allowAllEnabledTools: true,
        },
      },
      customPackages: {},
      skillPackages: {},
      mcpServers: {},
    },
    builtin: {
      websiteFetch: {
        maxChars: 6000,
        maxBytes: 1048576,
        maxUrlLength: 2048,
        timeoutMs: 15000,
        userAgent: "Yui-Chat/0.1",
        includeLinks: true,
        includeMedia: true,
      },
      github: {
        timeoutMs: 15000,
      },
      imageSearch: {
        defaultSource: "bing",
        enabledSources: ["bing", "baidu", "serp-bing", "serp-yandex", "pixiv"],
        fallbackEnabled: true,
        maxResults: 5,
        timeoutMs: 12000,
        downloadTimeoutMs: 30000,
        maxImageBytes: 33554432,
        pixivR18: false,
        pixivEndpoint: "https://api.lolicon.app/setu/v2",
        userAgent: "Mozilla/5.0 Yui-Chat/0.1",
      },
      webSearch: {
        defaultSource: "baidu-ai",
        enabledSources: ["baidu-ai", "tavily"],
        fallbackEnabled: true,
        maxResults: 5,
        timeoutMs: 30000,
      },
      scheduleTask: {
        enabled: true,
        maxPerUser: 1,
        cronMaxPerUser: 1,
        maxDelayMinutes: 43200,
        cronMinIntervalMinutes: 60,
        tickMs: 60000,
      },
      blockUser: {
        defaultMinutes: 30,
        maxMinutes: 720,
      },
      commandHandoff: {
        allowSend: true,
        requireMasterForPrivateTarget: true,
      },
      groupAdmin: {
        requireMaster: false,
      },
    },
  },
  skills: {
    disabled: [],
    sources: {},
    runtimeVariables: {},
  },
  response: {
    defaultMode: "text",
    quoteReply: true,
    replyConfirmType: 111,
    blockWords: [],
    promptBlockWords: [],
    removeCQCode: true,
    autoUsePicture: true,
    autoUsePictureThreshold: 1200,
    maxTextChunkLength: 1800,
    segmentation: {
      enabled: false,
      intervalMethod: "random",
      intervalMinSeconds: 1.5,
      intervalMaxSeconds: 3.5,
      thresholdChars: 150,
      mode: "regex",
      regex: ".*?[。？！!?；;~…]+|.+$",
      contentFilterRegex: "",
    },
    messageFilters: {
      enabled: true,
      runtimeVariables: {},
      filters: [],
    },
    tts: {
      enabled: false,
      mode: "openai-compatible",
      endpoint: "",
      apiKey: "",
      model: "tts-1",
      voice: "alloy",
      format: "mp3",
      maxChars: 300,
      timeoutMs: 30000,
      alsoSendText: true,
    },
    render: {
      enabled: true,
      engine: "sharp-svg",
      cache: true,
      cacheTtlMs: 86400000,
      width: 1120,
      maxTextChars: 8000,
      markdownEngine: "auto",
      markmapEngine: "auto",
      chatCardAsImage: true,
      helpAsImage: true,
      conversationListAsImage: true,
      mediaThumbnails: true,
      mediaThumbnailMaxCount: 3,
      mediaThumbnailMaxDataUrlChars: 800000,
      mediaThumbnail: {
        enabled: true,
        maxWidth: 320,
        maxHeight: 220,
        quality: 76,
        format: "jpeg",
        maxSourceBytes: 4194304,
      },
      delivery: {
        allowTargetSend: false,
        allowFilePathImages: false,
      },
      html: {
        enabled: false,
        maxUrlLength: 2048,
        maxHtmlChars: 200000,
        timeoutMs: 30000,
        waitUntil: "networkidle2",
        waitMs: 500,
        viewport: { width: 1280, height: 720 },
        deviceScaleFactor: 1,
      },
    },
    drawHandoff: {
      enabled: true,
      prefix: "#绘图",
      sendCommand: true,
      promptPrefix: "",
    },
  },
  memory: {
    enabled: true,
    injectProfile: true,
    injectRelevantFacts: true,
    maxFactsPerUser: 30,
    maxEpisodesPerScope: 100,
    maxMemoriesPerOwner: 500,
    maxLoadedMemoriesPerOwner: 600,
    cacheEntries: 384,
    flushDelayMs: 30000,
    promptBudgetChars: 2200,
    profileFactLimit: 5,
    relevantLimit: 5,
    autoWriteBack: true,
    retention: {
      shortTermHours: 72,
      episodeDays: 90,
      expiredGraceDays: 30,
    },
    retrieval: {
      // 对话注入的记忆条数，同时作为 adaptiveVector 的 FTS 触发阈值。
      // 当前默认 3 条，避免小规模记忆库在每轮对话都补一次向量召回。
      resultLimit: 3,
      promptTokenBudget: 350,
      ftsCandidateLimit: 20,
      // 向量召回是增强层：embeddingModel 留空时禁用，只用本地 FTS；
      // 填写 models 中支持 embedding 的模型名（如 bge-m3）后启用语义召回。
      vectorCandidateLimit: 20,
      embeddingModel: "",
      // 0 表示使用模型默认维度。
      embeddingDimensions: 0,
      embeddingTokensPerDay: 200000,
      // true：FTS 命中不足时才调向量（节约 API）；false：配置模型后每次召回都调。
      adaptiveVector: true,
    },
    groupCapture: {
      // 是否启用群消息归档子系统；实际采集仍须由主人逐群开启策略。
      enabled: true,
      // 新采集群的原文保留默认值；0 表示永久保留。继承本值的群会在修改后重算已存消息的过期时间。
      defaultRetentionDays: 30,
      // 新采集群的单日子窗口输入上限；消息不会被截断。单群可覆盖。
      defaultTokenLimit: 30000,
      // 新采集群的提炼提示词默认值；留空跟随内置默认词，单群可覆盖。
      promptTemplate: "",
      flushDelayMs: 1000,
      maxPendingMessages: 2000,
      maxSegmentsPerMessage: 64,
      maxTextChars: 8000,
      // 管理台手动从宿主补录聊天历史时的单次安全上限；不是自动拉取。
      historyBackfillMaxMessages: 500,
      windowCloseDelayMinutes: 15,
      scanIntervalMs: 300000,
      consolidation: {
        enabled: true,
        taskName: "replyer",
        // 新采集群的提炼模型默认值；留空跟随当前默认对话模型，单群可覆盖。
        modelName: "",
        maxAttempts: 3,
        // 推理型模型的思考 token 也计入输出上限；上限太小会把 candidates JSON 截断，导致提炼反复重试失败。
        // 可在系统默认或单群设置中调整，范围 256–65536。
        maxTokens: 4096,
        // 模型自报置信度低于该值的候选不入库；0 表示不过滤。
        minConfidence: 0.7,
        // 每轮扫描最多处理的提炼窗口数；大量补录后可临时调高加速消化。
        maxWindowsPerScan: 2,
      },
    },
  },
  context: {
    recentMessageCount: 20,
    captureGroups: true,
    capturePrivate: true,
    ignoreCommands: true,
    maxScopes: 1000,
    scopeTtlMs: 21600000,
    maxMessageChars: 220,
  },
  mediaRecognition: {
    enabled: true,
    recognitionModel: "",
    useAtAvatar: true,
    preferNativeVision: true,
    includeQuotedMedia: true,
    remoteFetch: {
      enabled: true,
      maxBytes: 4194304,
      timeoutMs: 10000,
      maxAttachments: 3,
      cacheTtlMs: 86400000,
      allowedMimeTypes: ["image/jpeg", "image/png", "image/webp", "image/gif"],
    },
  },
  mcp: {
    enabled: false,
    servers: {},
    serverTemplate: {
      enabled: true,
      transport: "stdio",
      url: "",
      command: "",
      args: [],
      env: {},
      category: "mcp",
      risk: "external",
      requiresFinalReply: true,
      execution: {},
      executionByAction: {},
      tags: [],
      policy: {
        externalNetwork: true,
      },
      toolPolicies: {
        example_tool_name: {
          risk: "medium",
          tags: ["example"],
          policy: {
            requiresMaster: false,
            requiresGroup: false,
            requiresGroupAdmin: false,
            highRisk: false,
            externalNetwork: true,
          },
        },
      },
    },
  },
  knowledge: {
    enabled: true,
    dynamicCapture: true,
    commandPrefixes: ["#", "/", "*"],
    excludedPlugins: [],
    excludedCommands: [],
    capturePrivate: false,
    captureGroups: true,
    maxEvents: 1000,
    flushDelayMs: 1500,
    indexing: {
      maxFileBytes: 10485760,
      maxChunksPerKnowledgeBase: 100000,
      // 管理员可按部署规模调整；设为 0 表示不启用本地每日 Token 上限。
      globalEmbeddingTokensPerDay: 2000000,
      batchSize: 32,
      concurrency: 2,
      maxAttempts: 3,
    },
    retrieval: {
      ftsCandidateLimit: 30,
      vectorCandidateLimit: 30,
      resultLimit: 4,
      resultTokenBudget: 800,
      minRelevance: 0.55,
      rerankTask: "retrieval_rerank",
      rerankMaxCandidates: 8,
      rerankInputTokenBudget: 1000,
      rerankMaxTokens: 128,
      rerankTimeoutMs: 5000,
      rerankCallsPerConversation: 3,
      rerankCallsPerDay: 100,
      rerankCacheTtlMs: 1800000,
    },
    commandRetrieval: {
      mode: "hybrid",
      lexicalWeight: 1,
      vectorWeight: 0.65,
      vectorCandidateLimit: 30,
    },
  },
  subAgent: {
    enabled: false,
    maxDepth: 1,
    maxTasksPerDispatch: 3,
    maxToolRounds: 4,
    maxToolCallsPerRound: 4,
    maxConcurrency: 3,
    maxDurationMs: 120000,
    task: "replyer",
    allowedTools: ["knowledge_manage", "memory_manage", "bilibili_media", "website_fetch", "web_search", "render_image"],
    systemPrompt: "你是一个子代理（sub-agent），由主对话派来独立完成一个明确的子任务。请充分利用可用工具收集信息，然后给出简洁、准确、可直接被主对话采用的结论；不要寒暄，也不要复述任务本身。",
  },
}
